/**
 * UV Unwrapper (G3-002)
 *
 * Smart UV unwrapping with angle-based segmentation, LSCM-style flattening,
 * and island packing. Produces globally coherent UVs for texturing.
 */

import { Mesh } from './Mesh';
import { Face } from './Face';
import { Vertex } from './Vertex';
import { Vec3 } from '../math/Vec3';

/**
 * Simple 2D vector for UV calculations
 */
class Vec2 {
  constructor(public x: number, public y: number) {}
}

/**
 * UV Island - a connected group of faces that share a UV chart
 */
export interface UVIsland {
  /** Island index */
  id: number;
  /** Face indices in this island */
  faceIndices: number[];
  /** Vertex indices (unique) in this island */
  vertexIndices: number[];
  /** Island-local UVs (indexed by vertex index) */
  uvs: Map<number, Vec2>;
  /** Bounding box in UV space */
  bounds: { uMin: number; uMax: number; vMin: number; vMax: number };
  /** Island area in UV space */
  uvArea: number;
  /** Island area in world space */
  worldArea: number;
}

/**
 * Unwrap options
 */
export interface UnwrapOptions {
  /** Angle threshold for segmentation (degrees, default 45) */
  angleThreshold?: number;
  /** Margin between islands (UV units, default 0.02) */
  margin?: number;
  /** Unwrapping method ('angle' | 'lscm', default 'angle') */
  method?: 'angle' | 'lscm';
  /** Normalize UVs to [0,1] after unwrapping */
  normalize?: boolean;
  /** When true, re-pack existing UVs instead of re-projecting.
   *  Preserves quality UVs generated by primitives (lathe, box, etc.)
   *  by identifying connected UV islands from existing coordinates
   *  and packing them into [0,1] space without re-projecting. */
  preserveExistingUVs?: boolean;
}

/**
 * Result of UV unwrapping
 */
export interface UnwrapResult {
  /** Mesh with updated UVs */
  mesh: Mesh;
  /** UV islands */
  islands: UVIsland[];
  /** Utilization (percentage of UV space used) */
  utilization: number;
  /** Maximum stretch ratio */
  maxStretch: number;
}

/**
 * Calculate face normal
 */
function calculateFaceNormal(mesh: Mesh, face: Face): Vec3 {
  if (face.indices.length < 3) return new Vec3(0, 1, 0);

  const p0 = mesh.vertices[face.indices[0]].position;
  const p1 = mesh.vertices[face.indices[1]].position;
  const p2 = mesh.vertices[face.indices[2]].position;

  const v1 = p1.sub(p0);
  const v2 = p2.sub(p0);
  const normal = v1.cross(v2);

  const len = normal.length();
  return len > 0.0001 ? normal.mul(1 / len) : new Vec3(0, 1, 0);
}

/**
 * Calculate face area in world space
 */
function calculateFaceArea(mesh: Mesh, face: Face): number {
  if (face.indices.length < 3) return 0;

  let area = 0;
  const p0 = mesh.vertices[face.indices[0]].position;

  for (let i = 1; i < face.indices.length - 1; i++) {
    const p1 = mesh.vertices[face.indices[i]].position;
    const p2 = mesh.vertices[face.indices[i + 1]].position;

    const v1 = p1.sub(p0);
    const v2 = p2.sub(p0);
    area += v1.cross(v2).length() * 0.5;
  }

  return area;
}

/**
 * Build face adjacency graph
 */
function buildFaceAdjacency(mesh: Mesh): Map<number, Set<number>> {
  const adjacency = new Map<number, Set<number>>();
  const edgeToFaces = new Map<string, number[]>();

  for (let fi = 0; fi < mesh.faces.length; fi++) {
    adjacency.set(fi, new Set());
    const face = mesh.faces[fi];

    for (let i = 0; i < face.indices.length; i++) {
      const v0 = face.indices[i];
      const v1 = face.indices[(i + 1) % face.indices.length];
      const edgeKey = v0 < v1 ? `${v0}-${v1}` : `${v1}-${v0}`;

      if (!edgeToFaces.has(edgeKey)) {
        edgeToFaces.set(edgeKey, []);
      }
      edgeToFaces.get(edgeKey)!.push(fi);
    }
  }

  // Connect faces that share edges
  for (const faces of edgeToFaces.values()) {
    for (let i = 0; i < faces.length; i++) {
      for (let j = i + 1; j < faces.length; j++) {
        adjacency.get(faces[i])!.add(faces[j]);
        adjacency.get(faces[j])!.add(faces[i]);
      }
    }
  }

  return adjacency;
}

/**
 * Segment mesh into UV islands based on normal angle threshold
 */
function segmentByAngle(mesh: Mesh, angleThreshold: number): number[][] {
  const cosThreshold = Math.cos(angleThreshold * Math.PI / 180);
  const adjacency = buildFaceAdjacency(mesh);
  const normals = mesh.faces.map(f => calculateFaceNormal(mesh, f));

  const visited = new Set<number>();
  const islands: number[][] = [];

  for (let startFace = 0; startFace < mesh.faces.length; startFace++) {
    if (visited.has(startFace)) continue;

    const island: number[] = [];
    const queue: number[] = [startFace];
    const baseNormal = normals[startFace];

    while (queue.length > 0) {
      const fi = queue.shift()!;
      if (visited.has(fi)) continue;

      // Check if face normal is within threshold of base normal
      const dot = normals[fi].dot(baseNormal);
      if (dot < cosThreshold && island.length > 0) {
        continue; // Normal too different, start new island later
      }

      visited.add(fi);
      island.push(fi);

      // Add adjacent faces to queue
      for (const adj of adjacency.get(fi)!) {
        if (!visited.has(adj)) {
          queue.push(adj);
        }
      }
    }

    if (island.length > 0) {
      islands.push(island);
    }
  }

  return islands;
}

/**
 * Project island faces to 2D using dominant plane.
 * Handles degenerate projections by trying multiple projection axes.
 */
function projectIslandToUV(mesh: Mesh, faceIndices: number[]): Map<number, Vec2> {
  const uvs = new Map<number, Vec2>();

  if (faceIndices.length === 0) return uvs;

  // Calculate average normal for the island
  let avgNormal = new Vec3(0, 0, 0);
  for (const fi of faceIndices) {
    avgNormal = avgNormal.add(calculateFaceNormal(mesh, mesh.faces[fi]));
  }
  avgNormal = avgNormal.normalize();

  // Try different projection planes and pick the one with largest UV area
  const projectionAxes: Array<{ uAxis: Vec3; vAxis: Vec3 }> = [];

  // Primary: based on average normal
  if (Math.abs(avgNormal.y) > 0.9) {
    projectionAxes.push({ uAxis: new Vec3(1, 0, 0), vAxis: new Vec3(0, 0, 1) });
  } else {
    let uAxis = new Vec3(0, 1, 0).cross(avgNormal).normalize();
    if (uAxis.length() < 0.001) {
      uAxis = new Vec3(1, 0, 0);
    }
    const vAxis = avgNormal.cross(uAxis).normalize();
    projectionAxes.push({ uAxis, vAxis });
  }

  // Fallback axes for small/degenerate islands
  projectionAxes.push({ uAxis: new Vec3(1, 0, 0), vAxis: new Vec3(0, 1, 0) }); // XY
  projectionAxes.push({ uAxis: new Vec3(1, 0, 0), vAxis: new Vec3(0, 0, 1) }); // XZ
  projectionAxes.push({ uAxis: new Vec3(0, 1, 0), vAxis: new Vec3(0, 0, 1) }); // YZ

  // Collect unique vertices
  const vertexSet = new Set<number>();
  for (const fi of faceIndices) {
    for (const vi of mesh.faces[fi].indices) {
      vertexSet.add(vi);
    }
  }
  const vertices = Array.from(vertexSet);

  // Try each projection and pick the one with largest bounding box area
  let bestProjection: Map<number, Vec2> | null = null;
  let bestArea = 0;

  for (const { uAxis, vAxis } of projectionAxes) {
    const projection = new Map<number, Vec2>();
    let uMin = Infinity, uMax = -Infinity;
    let vMin = Infinity, vMax = -Infinity;

    for (const vi of vertices) {
      const pos = mesh.vertices[vi].position;
      const u = pos.dot(uAxis);
      const v = pos.dot(vAxis);
      projection.set(vi, new Vec2(u, v));
      uMin = Math.min(uMin, u);
      uMax = Math.max(uMax, u);
      vMin = Math.min(vMin, v);
      vMax = Math.max(vMax, v);
    }

    const area = (uMax - uMin) * (vMax - vMin);
    if (area > bestArea) {
      bestArea = area;
      bestProjection = projection;
    }
  }

  return bestProjection || uvs;
}

/**
 * Normalize island UVs to [0,1] range, ensuring minimum size for rasterization
 */
function normalizeIslandUVs(uvs: Map<number, Vec2>): {
  uvs: Map<number, Vec2>;
  bounds: { uMin: number; uMax: number; vMin: number; vMax: number };
  scale: number;
} {
  let uMin = Infinity, uMax = -Infinity;
  let vMin = Infinity, vMax = -Infinity;

  for (const uv of uvs.values()) {
    uMin = Math.min(uMin, uv.x);
    uMax = Math.max(uMax, uv.x);
    vMin = Math.min(vMin, uv.y);
    vMax = Math.max(vMax, uv.y);
  }

  // Ensure minimum range to prevent degenerate triangles
  // At 512x512, 0.01 UV = 5 pixels, which is enough to rasterize
  const minRange = 0.01;
  let uRange = uMax - uMin;
  let vRange = vMax - vMin;

  // If range is too small, expand it
  if (uRange < minRange) {
    const center = (uMin + uMax) / 2;
    uMin = center - minRange / 2;
    uMax = center + minRange / 2;
    uRange = minRange;
  }
  if (vRange < minRange) {
    const center = (vMin + vMax) / 2;
    vMin = center - minRange / 2;
    vMax = center + minRange / 2;
    vRange = minRange;
  }

  const scale = Math.max(uRange, vRange);

  const normalized = new Map<number, Vec2>();
  for (const [vi, uv] of uvs) {
    normalized.set(vi, new Vec2(
      (uv.x - uMin) / scale,
      (uv.y - vMin) / scale
    ));
  }

  return {
    uvs: normalized,
    bounds: { uMin: 0, uMax: uRange / scale, vMin: 0, vMax: vRange / scale },
    scale
  };
}

/**
 * Calculate UV area of an island
 */
function calculateIslandUVArea(mesh: Mesh, faceIndices: number[], uvs: Map<number, Vec2>): number {
  let area = 0;

  for (const fi of faceIndices) {
    const face = mesh.faces[fi];
    if (face.indices.length < 3) continue;

    const uv0 = uvs.get(face.indices[0]);
    if (!uv0) continue;

    for (let i = 1; i < face.indices.length - 1; i++) {
      const uv1 = uvs.get(face.indices[i]);
      const uv2 = uvs.get(face.indices[i + 1]);
      if (!uv1 || !uv2) continue;

      // Triangle area using cross product
      const v1x = uv1.x - uv0.x;
      const v1y = uv1.y - uv0.y;
      const v2x = uv2.x - uv0.x;
      const v2y = uv2.y - uv0.y;
      area += Math.abs(v1x * v2y - v1y * v2x) * 0.5;
    }
  }

  return area;
}

/**
 * Create a UV island from face indices
 */
function createIsland(
  mesh: Mesh,
  faceIndices: number[],
  islandId: number
): UVIsland {
  // Project to UV space
  const rawUVs = projectIslandToUV(mesh, faceIndices);
  const { uvs, bounds } = normalizeIslandUVs(rawUVs);

  // Collect vertex indices
  const vertexSet = new Set<number>();
  for (const fi of faceIndices) {
    for (const vi of mesh.faces[fi].indices) {
      vertexSet.add(vi);
    }
  }

  // Calculate areas
  const uvArea = calculateIslandUVArea(mesh, faceIndices, uvs);
  let worldArea = 0;
  for (const fi of faceIndices) {
    worldArea += calculateFaceArea(mesh, mesh.faces[fi]);
  }

  return {
    id: islandId,
    faceIndices,
    vertexIndices: Array.from(vertexSet),
    uvs,
    bounds,
    uvArea,
    worldArea
  };
}

/**
 * Rectangle for tracking free space in packing
 */
interface FreeRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Improved UV island packing using maxrects-style algorithm
 * Places islands in the best-fit free rectangle to minimize wasted space
 */
function packIslands(islands: UVIsland[], margin: number): void {
  if (islands.length === 0) return;

  // Enforce minimum margin to prevent dilation overlap
  const effectiveMargin = Math.max(margin, 0.02);

  // Sort islands by height (tallest first) for better packing
  const sorted = [...islands].sort((a, b) => {
    const aHeight = a.bounds.vMax - a.bounds.vMin;
    const bHeight = b.bounds.vMax - b.bounds.vMin;
    if (Math.abs(aHeight - bHeight) < 0.001) {
      // If same height, sort by area
      const aArea = (a.bounds.uMax - a.bounds.uMin) * aHeight;
      const bArea = (b.bounds.uMax - b.bounds.uMin) * bHeight;
      return bArea - aArea;
    }
    return bHeight - aHeight;
  });

  // Calculate total area to determine scale factor
  let totalArea = 0;
  for (const island of sorted) {
    const w = island.bounds.uMax - island.bounds.uMin + effectiveMargin;
    const h = island.bounds.vMax - island.bounds.vMin + effectiveMargin;
    totalArea += w * h;
  }

  // Scale factor - be more generous to give islands more space
  const availableSpace = 1 - 2 * effectiveMargin;
  const availableArea = availableSpace * availableSpace * 0.65;
  const scaleFactor = totalArea > availableArea ? Math.sqrt(availableArea / totalArea) : 1;

  // Minimum size for islands
  const minIslandSize = 0.025; // Slightly smaller to allow more islands to fit

  // Initialize free rectangles list with the entire usable area
  const freeRects: FreeRect[] = [{
    x: effectiveMargin,
    y: effectiveMargin,
    width: 1 - 2 * effectiveMargin,
    height: 1 - 2 * effectiveMargin
  }];

  // Place each island
  for (const island of sorted) {
    // Calculate island size after scaling
    const islandWidth = Math.max(minIslandSize, (island.bounds.uMax - island.bounds.uMin) * scaleFactor);
    const islandHeight = Math.max(minIslandSize, (island.bounds.vMax - island.bounds.vMin) * scaleFactor);

    // Required size including margin
    const reqWidth = islandWidth + effectiveMargin;
    const reqHeight = islandHeight + effectiveMargin;

    // Find best fitting free rectangle (best short side fit)
    let bestRect: FreeRect | null = null;
    let bestRectIndex = -1;
    let bestShortSideFit = Infinity;

    for (let i = 0; i < freeRects.length; i++) {
      const rect = freeRects[i];
      if (rect.width >= reqWidth && rect.height >= reqHeight) {
        const leftoverH = rect.width - reqWidth;
        const leftoverV = rect.height - reqHeight;
        const shortSideFit = Math.min(leftoverH, leftoverV);

        if (shortSideFit < bestShortSideFit) {
          bestShortSideFit = shortSideFit;
          bestRect = rect;
          bestRectIndex = i;
        }
      }
    }

    if (!bestRect) {
      // No space found - try to fit in any remaining space
      // Scale down this island to fit somewhere
      let placed = false;
      for (let i = 0; i < freeRects.length && !placed; i++) {
        const rect = freeRects[i];
        if (rect.width >= minIslandSize + effectiveMargin &&
            rect.height >= minIslandSize + effectiveMargin) {
          // Fit island into this rect at minimum size
          const fitWidth = Math.min(islandWidth, rect.width - effectiveMargin);
          const fitHeight = Math.min(islandHeight, rect.height - effectiveMargin);

          placeIsland(island, rect.x, rect.y, fitWidth, fitHeight, effectiveMargin);
          splitFreeRect(freeRects, i, fitWidth + effectiveMargin, fitHeight + effectiveMargin);
          placed = true;
        }
      }
      if (!placed) {
        // Last resort: place at minimum size at origin (will overlap but won't crash)
        placeIsland(island, effectiveMargin, effectiveMargin, minIslandSize, minIslandSize, effectiveMargin);
      }
      continue;
    }

    // Place island in the best rectangle
    placeIsland(island, bestRect.x, bestRect.y, islandWidth, islandHeight, effectiveMargin);

    // Split the free rectangle
    splitFreeRect(freeRects, bestRectIndex, reqWidth, reqHeight);

    // Remove any fully contained rectangles (cleanup)
    removeDuplicateFreeRects(freeRects);
  }
}

/**
 * Place an island at the specified position with the specified size
 */
function placeIsland(
  island: UVIsland,
  x: number, y: number,
  width: number, height: number,
  _margin: number  // Reserved for future use (padding around islands)
): void {
  const originalWidth = island.bounds.uMax - island.bounds.uMin;
  const originalHeight = island.bounds.vMax - island.bounds.vMin;

  const scaleU = width / Math.max(0.001, originalWidth);
  const scaleV = height / Math.max(0.001, originalHeight);

  const offsetU = x - island.bounds.uMin * scaleU;
  const offsetV = y - island.bounds.vMin * scaleV;

  const newUVs = new Map<number, Vec2>();
  for (const [vi, uv] of island.uvs) {
    const newU = Math.max(0, Math.min(1, uv.x * scaleU + offsetU));
    const newV = Math.max(0, Math.min(1, uv.y * scaleV + offsetV));
    newUVs.set(vi, new Vec2(newU, newV));
  }
  island.uvs = newUVs;

  island.bounds = {
    uMin: Math.max(0, x),
    uMax: Math.min(1, x + width),
    vMin: Math.max(0, y),
    vMax: Math.min(1, y + height)
  };
}

/**
 * Split a free rectangle after placing an island
 * Uses guillotine split - creates two new rectangles from the remaining space
 */
function splitFreeRect(freeRects: FreeRect[], index: number, usedWidth: number, usedHeight: number): void {
  const rect = freeRects[index];

  // Remove the original rectangle
  freeRects.splice(index, 1);

  // Create new rectangles from remaining space
  // Right remainder
  if (rect.width - usedWidth > 0.01) {
    freeRects.push({
      x: rect.x + usedWidth,
      y: rect.y,
      width: rect.width - usedWidth,
      height: rect.height
    });
  }

  // Bottom remainder
  if (rect.height - usedHeight > 0.01) {
    freeRects.push({
      x: rect.x,
      y: rect.y + usedHeight,
      width: usedWidth, // Only the width we used, not the full rect
      height: rect.height - usedHeight
    });
  }
}

/**
 * Remove free rectangles that are fully contained within others
 */
function removeDuplicateFreeRects(freeRects: FreeRect[]): void {
  for (let i = freeRects.length - 1; i >= 0; i--) {
    for (let j = 0; j < freeRects.length; j++) {
      if (i === j) continue;
      const a = freeRects[i];
      const b = freeRects[j];
      // Check if a is fully contained in b
      if (a.x >= b.x && a.y >= b.y &&
          a.x + a.width <= b.x + b.width &&
          a.y + a.height <= b.y + b.height) {
        freeRects.splice(i, 1);
        break;
      }
    }
  }
}

/**
 * Apply island UVs to mesh vertices
 */
function applyIslandsToMesh(mesh: Mesh, islands: UVIsland[]): Mesh {
  // Create new mesh with updated UVs, copying material slots from original
  const newMesh = new Mesh([], [], [...mesh.materialSlots]);

  // Map from original vertex index to new vertex indices (may be duplicated for different islands)
  const vertexMap = new Map<string, number>(); // "originalIdx-islandId" -> newIdx

  for (const island of islands) {
    for (const fi of island.faceIndices) {
      const face = mesh.faces[fi];
      const newIndices: number[] = [];

      for (const vi of face.indices) {
        const key = `${vi}-${island.id}`;
        let newVi: number;

        if (vertexMap.has(key)) {
          newVi = vertexMap.get(key)!;
        } else {
          // Create new vertex with UV from island, preserving smoothGroup for normal averaging
          const oldVertex = mesh.vertices[vi];
          const uv = island.uvs.get(vi) ?? new Vec2(0, 0);
          const newVertex = new Vertex(
            oldVertex.position.clone(),
            {
              normal: oldVertex.attributes.normal?.clone(),
              color: oldVertex.attributes.color ? [...oldVertex.attributes.color] as [number, number, number] : undefined,
              smoothGroup: oldVertex.attributes.smoothGroup,
              uv: [uv.x, uv.y] as [number, number]
            }
          );
          newVi = newMesh.addVertex(newVertex);
          vertexMap.set(key, newVi);
        }

        newIndices.push(newVi);
      }

      const newFace = new Face(newIndices);
      newFace.color = face.color;
      newFace.materialSlotIndex = face.materialSlotIndex;
      newMesh.addFace(newFace);
    }
  }

  return newMesh;
}

/**
 * Calculate unwrap statistics
 */
function calculateStats(islands: UVIsland[]): { utilization: number; maxStretch: number } {
  let totalUVArea = 0;
  let maxStretch = 0;

  for (const island of islands) {
    totalUVArea += island.uvArea;

    // Stretch = ratio of UV area to world area (normalized)
    if (island.worldArea > 0.0001) {
      const avgScale = Math.sqrt(island.uvArea / island.worldArea);
      // Compare to other islands
      for (const other of islands) {
        if (other.worldArea > 0.0001 && other !== island) {
          const otherScale = Math.sqrt(other.uvArea / other.worldArea);
          const ratio = avgScale > otherScale ? avgScale / otherScale : otherScale / avgScale;
          maxStretch = Math.max(maxStretch, ratio);
        }
      }
    }
  }

  // Utilization = UV area used / total [0,1] space
  const utilization = Math.min(1, totalUVArea) * 100;

  return { utilization, maxStretch: maxStretch || 1 };
}

/**
 * Unwrap mesh UVs using smart segmentation and packing
 */
export function unwrapMesh(mesh: Mesh, options: UnwrapOptions = {}): UnwrapResult {
  const {
    angleThreshold = 45,
    margin = 0.02,
    normalize = true,
    preserveExistingUVs = false
  } = options;

  // Check if mesh already has UVs and re-pack mode is requested
  const hasExistingUVs = preserveExistingUVs && mesh.vertices.some(v => v.attributes.uv !== undefined);

  if (hasExistingUVs) {
    return repackExistingUVs(mesh, margin);
  }

  // Segment mesh into islands
  const faceGroups = segmentByAngle(mesh, angleThreshold);

  // Create islands with projected UVs
  const islands: UVIsland[] = faceGroups.map((faces, i) =>
    createIsland(mesh, faces, i)
  );

  // Pack islands into [0,1] space
  if (normalize) {
    packIslands(islands, margin);
  }

  // Apply UVs to mesh
  const unwrappedMesh = applyIslandsToMesh(mesh, islands);

  // Calculate statistics
  const stats = calculateStats(islands);

  return {
    mesh: unwrappedMesh,
    islands,
    utilization: stats.utilization,
    maxStretch: stats.maxStretch
  };
}

/**
 * UVUnwrapper class for stateful unwrapping with options
 */
export class UVUnwrapper {
  private options: UnwrapOptions;

  constructor(options: UnwrapOptions = {}) {
    this.options = options;
  }

  /**
   * Unwrap a mesh
   */
  unwrap(mesh: Mesh): UnwrapResult {
    return unwrapMesh(mesh, this.options);
  }

  /**
   * Set angle threshold
   */
  setAngleThreshold(degrees: number): void {
    this.options.angleThreshold = degrees;
  }

  /**
   * Set margin
   */
  setMargin(margin: number): void {
    this.options.margin = margin;
  }
}

/**
 * Detect whether a mesh has overlapping UV islands (G3-004).
 *
 * Uses flood-fill island detection and duplicate-detection to determine
 * if UV islands overlap. Returns overlap status and island counts so the
 * caller can decide whether repacking is needed.
 */
export function detectUVOverlap(mesh: Mesh): {
  hasOverlap: boolean;
  islandCount: number;
  uniqueIslandCount: number;
} {
  const hasUVs = mesh.vertices.some(v => v.attributes.uv !== undefined);
  if (!hasUVs) return { hasOverlap: false, islandCount: 0, uniqueIslandCount: 0 };

  const islands = detectIslandsFromExistingUVs(mesh);
  if (islands.length <= 1) return { hasOverlap: false, islandCount: islands.length, uniqueIslandCount: islands.length };

  const duplicateOf = findDuplicateIslands(islands);
  const uniqueCount = islands.length - duplicateOf.size;

  // Duplicates by definition overlap (identical UV bounds)
  if (duplicateOf.size > 0) {
    return { hasOverlap: true, islandCount: islands.length, uniqueIslandCount: uniqueCount };
  }

  // Check AABB overlap among unique islands
  let hasOverlap = false;
  for (let i = 0; i < islands.length && !hasOverlap; i++) {
    for (let j = i + 1; j < islands.length && !hasOverlap; j++) {
      const a = islands[i].bounds;
      const b = islands[j].bounds;
      if (a.uMin < b.uMax && a.uMax > b.uMin && a.vMin < b.vMax && a.vMax > b.vMin) {
        hasOverlap = true;
      }
    }
  }

  return { hasOverlap, islandCount: islands.length, uniqueIslandCount: uniqueCount };
}

/**
 * Compute recommended atlas texture resolution based on scene complexity (G3-004).
 *
 * Scales up from baseResolution for complex composed scenes:
 * - <100 triangles per material group → 512
 * - 100-1000 → 1024
 * - 1000+ → 2048
 */
export function computeAtlasResolution(mesh: Mesh, baseResolution: number = 512): number {
  const trisByMaterial = new Map<number, number>();
  for (const face of mesh.faces) {
    const slot = face.materialSlotIndex ?? 0;
    const triCount = Math.max(0, face.indices.length - 2);
    trisByMaterial.set(slot, (trisByMaterial.get(slot) ?? 0) + triCount);
  }

  const maxTrisPerMaterial = Math.max(...trisByMaterial.values(), 1);

  if (maxTrisPerMaterial >= 1000) return Math.max(baseResolution, 2048);
  if (maxTrisPerMaterial >= 100) return Math.max(baseResolution, 1024);
  return Math.max(baseResolution, 512);
}

/**
 * Detect UV islands from existing UV coordinates via edge-based flood-fill.
 * Shared helper for detectUVOverlap and repackExistingUVs.
 */
function detectIslandsFromExistingUVs(mesh: Mesh): UVIsland[] {
  const edgeToFaces = new Map<string, number[]>();
  for (let fi = 0; fi < mesh.faces.length; fi++) {
    const face = mesh.faces[fi];
    for (let i = 0; i < face.indices.length; i++) {
      const a = face.indices[i];
      const b = face.indices[(i + 1) % face.indices.length];
      const key = a < b ? `${a}-${b}` : `${b}-${a}`;
      if (!edgeToFaces.has(key)) edgeToFaces.set(key, []);
      edgeToFaces.get(key)!.push(fi);
    }
  }

  const visited = new Set<number>();
  const faceGroups: number[][] = [];

  for (let fi = 0; fi < mesh.faces.length; fi++) {
    if (visited.has(fi)) continue;

    const group: number[] = [];
    const stack = [fi];
    while (stack.length > 0) {
      const current = stack.pop()!;
      if (visited.has(current)) continue;
      visited.add(current);
      group.push(current);

      const face = mesh.faces[current];
      for (let i = 0; i < face.indices.length; i++) {
        const a = face.indices[i];
        const b = face.indices[(i + 1) % face.indices.length];
        const key = a < b ? `${a}-${b}` : `${b}-${a}`;
        const adjacent = edgeToFaces.get(key);
        if (adjacent) {
          for (const adj of adjacent) {
            if (!visited.has(adj)) stack.push(adj);
          }
        }
      }
    }
    faceGroups.push(group);
  }

  return faceGroups.map((faceIndices, id) => {
    const vertexIndices = new Set<number>();
    const uvs = new Map<number, Vec2>();

    for (const fi of faceIndices) {
      for (const vi of mesh.faces[fi].indices) {
        vertexIndices.add(vi);
        const uv = mesh.vertices[vi].attributes.uv;
        if (uv) {
          uvs.set(vi, new Vec2(uv[0], uv[1]));
        } else {
          uvs.set(vi, new Vec2(0, 0));
        }
      }
    }

    let uMin = Infinity, uMax = -Infinity, vMin = Infinity, vMax = -Infinity;
    for (const uv of uvs.values()) {
      uMin = Math.min(uMin, uv.x);
      uMax = Math.max(uMax, uv.x);
      vMin = Math.min(vMin, uv.y);
      vMax = Math.max(vMax, uv.y);
    }

    let worldArea = 0;
    for (const fi of faceIndices) {
      worldArea += calculateFaceArea(mesh, mesh.faces[fi]);
    }
    const uvArea = Math.max(0.0001, (uMax - uMin) * (vMax - vMin));

    return {
      id,
      faceIndices,
      vertexIndices: [...vertexIndices],
      uvs,
      bounds: { uMin, uMax, vMin, vMax },
      uvArea,
      worldArea
    };
  });
}

/**
 * Find near-duplicate UV islands (bounds within 1% tolerance).
 * Returns map of duplicateIdx → canonicalIdx.
 * Shared helper for detectUVOverlap and repackExistingUVs.
 */
function findDuplicateIslands(islands: UVIsland[]): Map<number, number> {
  const TOLERANCE = 0.01;
  const duplicateOf = new Map<number, number>();
  for (let i = 0; i < islands.length; i++) {
    if (duplicateOf.has(i)) continue;
    const a = islands[i].bounds;
    const aW = a.uMax - a.uMin, aH = a.vMax - a.vMin;
    if (aW < 1e-6 || aH < 1e-6) continue;
    for (let j = i + 1; j < islands.length; j++) {
      if (duplicateOf.has(j)) continue;
      const b = islands[j].bounds;
      const bW = b.uMax - b.uMin, bH = b.vMax - b.vMin;
      if (Math.abs(aW - bW) / Math.max(aW, bW) < TOLERANCE &&
          Math.abs(aH - bH) / Math.max(aH, bH) < TOLERANCE &&
          Math.abs(a.uMin - b.uMin) < TOLERANCE &&
          Math.abs(a.vMin - b.vMin) < TOLERANCE) {
        duplicateOf.set(j, i);
      }
    }
  }
  return duplicateOf;
}

/**
 * Re-pack existing UVs without re-projecting.
 *
 * Preserves quality UVs generated by primitives (lathe cylindrical UVs,
 * box planar UVs, etc.) by identifying connected UV islands from existing
 * coordinates and packing them into [0,1] space.
 *
 * This avoids the information loss that happens when unwrapMesh() discards
 * the original UVs and re-projects from scratch.
 */
export function repackExistingUVs(mesh: Mesh, margin: number = 0.02): UnwrapResult {
  const islands = detectIslandsFromExistingUVs(mesh);

  // Detect and merge near-duplicate islands (e.g. radial-array teeth that all
  // have the same UV footprint). Duplicate islands waste atlas space and cause
  // overflow/stacking when there are many repeated instances (e.g. 23 teeth).
  const duplicateOf = findDuplicateIslands(islands);

  if (duplicateOf.size > 0) {
    for (const [dupIdx, canonIdx] of duplicateOf) {
      const dup = islands[dupIdx];
      const canon = islands[canonIdx];
      const dupW = dup.bounds.uMax - dup.bounds.uMin;
      const dupH = dup.bounds.vMax - dup.bounds.vMin;
      for (const [vi, dupUV] of dup.uvs) {
        const t = dupW > 1e-6 ? (dupUV.x - dup.bounds.uMin) / dupW : 0;
        const s = dupH > 1e-6 ? (dupUV.y - dup.bounds.vMin) / dupH : 0;
        const canonW = canon.bounds.uMax - canon.bounds.uMin;
        const canonH = canon.bounds.vMax - canon.bounds.vMin;
        dup.uvs.set(vi, new Vec2(
          canon.bounds.uMin + t * canonW,
          canon.bounds.vMin + s * canonH
        ));
      }
      dup.bounds = { ...canon.bounds };
    }
  }

  // Pack islands into [0,1] space (reuses the existing packing algorithm)
  packIslands(islands, margin);

  // Apply the repacked UVs to the mesh (creates new mesh with UV seam splits)
  const repackedMesh = applyIslandsToMesh(mesh, islands);

  const stats = calculateStats(islands);

  return {
    mesh: repackedMesh,
    islands,
    utilization: stats.utilization,
    maxStretch: stats.maxStretch
  };
}
